## Numpy Array operations

In [3]:
import numpy as np

In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [8]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row: ", arr_2d[1])
print("Entire row: ", arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
Entire row:  [2 5 8]


## Sorting

In [14]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column [[1 1]
 [2 2]
 [3 3]]


## Filter


In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


## Filter with mask

In [19]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [6]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) #index bigger than 5
print("NP where", numbers[where_result])   #numbers greater than 5

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [29]:
condition_array = np.where(numbers > 5, "true",  "false")
print(condition_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [16]:
numbers=[1,2,3,4,5,6,7,8,9,10]
if numbers is greater than 5:
    numbers*4
else:
    numbers

SyntaxError: invalid syntax (3791770424.py, line 2)

In [7]:
condition_array = np.where(numbers > 5, numbers, numbers)
print(condition_array)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, numbers*4,  numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and removing data

In [32]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### array compatibilty

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes False


In [17]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))     #vstack : to add new columns vertically
print(original)
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))   #hstack : to add new columns horizontally
print("With new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column [[1 2 7]
 [3 4 8]]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
